name: Build and Deploy to AKS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Get image version from Chart.yaml
        id: get-version
        run: |
          pwd
          VERSION=$(grep '^appVersion:' ./helm_values/Chart.yaml | awk '{print $2}' | tr -d '"')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to ACR
        run: |
          az acr login --name sanketsacr

      - name: Build and push Docker image
        run: |
          docker build -t sanketsacr.azurecr.io/portfolio:${{ steps.get-version.outputs.version }} .
          docker push sanketsacr.azurecr.io/portfolio:${{ steps.get-version.outputs.version }}

      - name: Set AKS context
        run: |
          az aks get-credentials --resource-group rg-portfolio-content --name my-first-aks

      - name: Deploy to AKS
        run: |
          helm upgrade --install portfolio ./chart \
                --set image.tag=${{ steps.get-version.outputs.version }} \
                --wait